CREATE TABLE Sensor
(
    id          INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR(255) NOT NULL,
    created_at  TIMESTAMP    NOT NULL,
    modified_at TIMESTAMP    NOT NULL
);

CREATE TABLE Measurement
(
    id          INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    sensor_id   INT REFERENCES Sensor (id) NOT NULL,
    value       DECIMAL                    NOT NULL,
    raining     BOOLEAN                    NOT NULL,
    created_at  TIMESTAMP                  NOT NULL,
    modified_at TIMESTAMP                  NOT NULL
);

INSERT INTO public.sensor (id, name, created_at, modified_at) VALUES (1, 'Capybara', '2025-01-25 20:53:18.344963', '2025-01-25 20:53:18.344963');
INSERT INTO public.sensor (id, name, created_at, modified_at) VALUES (2, 'CapybaraS', '2025-01-25 20:55:02.936686', '2025-01-25 20:55:02.936686');
INSERT INTO public.sensor (id, name, created_at, modified_at) VALUES (3, 'DelphingtonScaner', '2025-01-25 21:43:38.048520', '2025-01-25 21:43:38.048520');
