CREATE TABLE Sensor
(
    id          INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name        VARCHAR(255) NOT NULL,
    created_at  TIMESTAMP    NOT NULL,
    modified_at TIMESTAMP    NOT NULL
);

CREATE TABLE Measurement
(
    id          INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    sensor_id   INT REFERENCES Sensor (id) NOT NULL,
    value       DECIMAL                    NOT NULL,
    raining     BOOLEAN                    NOT NULL,
    created_at  TIMESTAMP                  NOT NULL,
    modified_at TIMESTAMP                  NOT NULL
);