CREATE TABLE Person(
    id   INT GENERATED BY DEFAULT AS IDENTITY primary key,
    name text NOT NULL UNIQUE,
    year int  NOT NULL check ( year >0)
);


CREATE TABLE book(
    id int GENERATED BY DEFAULT AS IDENTITY primary key,
    id int NOT NULL;
    name text NOT NULL,
    author text NOT NULL,
    year int NOT NULL check (year >0)
);

